

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: timeline
spec:
  replicas: 2
  selector: { matchLabels: { app: gateway } }
  template:
    metadata: { labels: { app: gateway } }
    spec:
      containers:
        - name: gateway
          image: your-dockerhub/gateway:latest
          ports: [{ containerPort: 8000 }]
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: timeline
spec:
  selector: { app: gateway }
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
