

version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  cassandra:
    image: cassandra:4.1
    ports: ["9042:9042"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  gateway:
    build: ./services/gateway
    environment:
      - PORT=8000
    ports: ["8080:8000"]
    depends_on: [tweet_write, timeline_read]

  tweet_write:
    build: ./services/tweet-write
    environment:
      - PORT=8000
    ports: ["8081:8000"]
    depends_on: [kafka, cassandra]

  timeline_read:
    build: ./services/timeline-read
    environment:
      - PORT=8000
    ports: ["8082:8000"]
    depends_on: [redis, cassandra, ranker]

  fanout:
    build: ./services/fanout
    ports: ["8083:8000"]
    depends_on: [kafka, redis, cassandra]

  ranker:
    build: ./services/ranker
    ports: ["8084:8000"]

  graph:
    build: ./services/graph
    ports: ["8085:8000"]
    depends_on: [cassandra]

  counters:
    build: ./services/counters
    ports: ["8086:8000"]
    depends_on: [kafka, cassandra]

  idgen:
    build: ./services/idgen
    ports: ["8087:8000"]

  search:
    build: ./services/search
    ports: ["8088:8000"]
